batch_size:
- 16
- 16
- 16
- 16
- 8
- 4
d_extra_steps: 1
data_path: /home/ducanh/Ptycho_data/data//comp_data/
filters:
- 512
- 512
- 512
- 512
- 256
- 128
- 64
- 32
filters_scale: 0.5
input_shape:
- 128
- 128
- 2
latent_dim: 32
n_epochs: 32
name: PGAN
train_dir: null
plot_fn: plot_cxdi_NP
