batch_size:
- 32
- 32
- 32
- 32
- 32
- 16
- 8
d_extra_steps: 1
data_path: ./data/chart_data/
filters:
- 512
- 512
- 512
- 512
- 256
- 128
- 64
- 32
filters_scale: 1
input_shape:
- 256
- 256
- 1
latent_dim: 32
n_epochs: 32
name: PGAN
plot_fn: plot_cxdi_chart
train_dir: null
