batch_size:
- 8
- 8
- 4
- 2
d_extra_steps: 1
data_path: ./data/rubber_data/
filters:
- 512
- 512
- 512
- 512
- 256
- 128
- 64
- 32
filters_scale: 0.5
input_shape:
- 32
- 32
- 32
- 3
latent_dim: 32
n_epochs: 16
name: PGAN3D
plot_fn: plot_xafs_3d
train_dir: null
